# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Mahmood GholipourChoubeh
title: Software developer
email: mahmood.gholipour@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  mahmoodgh
  # stackoverflow_username: "00000001"
  #dribbble_username: jekyll
  #facebook_username: jekyll
  #flickr_username: jekyll
  #instagram_username: jekyll
linkedin_username: mahmood-gholipour
  #xing_username: jekyll
  #pinterest_username: jekyll
  #youtube_username: jekyll
  #orcid_username: 0000-0000-0000-0000
googlescholar_username: O2keDT4AAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs 
  Hi!,
  
  System-Level Software Engineer with experience in Linux-based C and C++ development, specializing in distributed motion control systems. Skilled in designing extensible APIs, implementing multithreaded and concurrent components, and developing high-reliability server-side software. Fast learner, self-motivated, and a team player with strong communication skills. Experienced in debugging complex systems, refactoring code, and improving software quality through automated testing. In addition to technical expertise, I have a keen eye for detail and a passion for solving intricate technical challenges, with additional experience in networking and network security.
  
  I am actively seeking a challenging role where I can leverage my extensive technical skills, problem-solving abilities, and effective communication to drive innovation and excellence.  
content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Concordia University
        link: 
        link_text: 
        additional_links:
        quote: >
           Master of Science in Information Systems Security, Montreal, Quebec, Canada, 2023
          
        description: | #this will include new lines to allow paragraphs
          - Thesis: Building Cross-Cluster Security Models for Edge-Core Env. Involving Multiple Kubernetes Clusters
          - Academic Supervisors: Dr. Lingyu Wang, Dr. Suryadipta Majumdar
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Tehran University
        link: 
        link_text: 
        additional_links:
        quote: >
           Master’s in Computer Engineering, University of Tehran, Tehran, Iran, 2013
          
        description: | #this will include new lines to allow paragraphs
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Arak University
        link: 
        link_text: 
        additional_links:
        quote: >
            Bachelor’s in Computer Engineering, Arak University, Iran, 2009
          
        description: | #this will include new lines to allow paragraphs


  - title: Recent Work and Industrial Experience
    layout: list
    content:
      - layout: left
        title: Polaris Motion Co.
        sub_title: System Software Engineer
        caption: Jun. 2024 - Jan. 2026
        link: 
        quote: >
          MAIN SKILLS & TOOLS: C/C++, Python, Bash, Linux, GDB, CMake, VSCode, Git, Agile/Scrum
        description: | # this will include new lines to allow paragraphs
          - Designed, developed, and maintained high-performance system software using C++ in Linux environments
          - Integrated autotuning functionality by implementing control algorithms provided by the control engineering team
          - Developed and exposed public APIs in C++ enabling customers to customize handwheel thread behavior
          - Implemented event-driven mechanisms and queues for G-code param to enable monitoring runtime changes
          - Contributed to auto-configuration capabilities using XML and XSD to support correct device detection
          - Modernized legacy code by refactoring and redesigning in modern C++, improving system robustness
          - Developed automated regression & unit tests using Google Test to improve reliability and prevent regressions
          - Debugged and troubleshot complex customer-reported issues using GDB, Valgrind, core dumps, and system logs to identify root causes and implement fixes
          - Collaborated with cross-functional teams (firmware, control, QA) to deliver new features and resolve issues
          - Worked with Git-based development workflows, including feature branching, pull requests, and code reviews, to maintain code quality and consistency
          - Participated in Agile/Scrum development processes, technical discussions, and sprint planning activities   
    layout: list
    content:
      - layout: left
        title: ARC lab. NSERC Program (Concordia + Ericsson)
        sub_title: Researcher and Developer
        caption: Sep. 2020 - Aug. 2023
        link: https://arc.encs.concordia.ca/index.html
        quote: >
          M.Sc. Student (R&D) in the project ”Compliance-based security in NFV/SDN with application to 5G”
        description: | # this will include new lines to allow paragraphs
          - Developed an approach to build a cross-cluster security model for edge-core environment involving multiple kubernetes clusters
          - Collaborated with a team from academia and industry to provide a proactive security policy enforcement 
            for containers and the development of a proof of concept
          - Modified Free5GC source codes to increase the precision of logs timestamps (Merged into vendor’s official code base)
          - Deployed a multi-Kubernetes cluster version of Free5GC
          - Deployed a testbed in dedicated servers to provide a container based environment (single and multiple-cluster version) orchestrated by Kubernetes
          - Contributed in technical presentations and demos in project steering and in major industrial event at Ericsson
  - title: Technichal Skills and Tools
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Programming Languages:** Proficient in C/C++, Python, Bash Scripting; exposed to Java, C#
      - **Operarting Systems:** Linux, Unix, Windows
      - **Tools and IDE:** Vim, VSCode, QTCreator, GDB, Valgrind, CMake
      - **Software Development Practice:** OOP, TDD, SOLID, Agile/Scrum, CI/CD, Git and GitHub
      - **Networking & Security:** Network+, CCNA, IPTables, Wireshark, VPP, DPDK, PktGen, TRex, TCPDump
      - **Container Technologies and Tools:** Kubernetes, Docker
      - **5G Core Network:** Free5GC
      - **Collaboration & Project Tools:** Git, Jira, Confluence, Upsource
      - **Motion Control:** CNC, G-code, distributed motion control platforms
      
#This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

#Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
